'use strict';
const $=id=>document.getElementById(id),fmt=(n,d=1)=>Number(n).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}),km=n=>fmt(n/1000)+' km';
const state={vehicle:'bike',mode:'normal',points:{origin:null,stop:null,destination:null},hasStop:false,route:null,config:null,revision:0,request:0,selecting:null,saved:[],publicStations:[],stationTab:'public',pendingStation:null,stationsBusy:false};
let map,routeLayers,pointLayers,stationLayers,toastTimer,searchResolve;
function notify(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,error?10000:6500);}
function config(){return {vehicle:state.vehicle,mode:state.mode,battery:Number($('battery').value),range:Number($('fullRange').value),weight:Number($('weight').value),chargeTarget:state.hasStop?Number($('chargeTarget').value):80,chargeMinutes:state.hasStop?Number($('chargeMinutes').value):60};}
function validConfig(c){return Object.hasOwn(VEHICLES,c.vehicle)&&['eco','normal','sport'].includes(c.mode)&&[c.battery,c.range,c.weight,c.chargeTarget,c.chargeMinutes].every(Number.isFinite)&&c.battery>=0&&c.battery<=100&&c.range>=1&&c.range<=1000&&c.weight>=20&&c.weight<=400&&c.chargeTarget>=1&&c.chargeTarget<=100&&c.chargeMinutes>=1&&c.chargeMinutes<=1440;}
function cancelSelection(){state.selecting=null;$('selectionBanner').hidden=true;if(map)map.getContainer().style.cursor='';}
function clearResults(){state.route=null;state.energy=null;state.request++;routeLayers?.clearLayers();$('result').className='result empty';$('emptyResult').hidden=false;$('resultContent').hidden=true;$('mapTitle').textContent='Explore seu próximo trajeto';}
function invalidate(){state.revision++;clearResults();}
function refreshModel(){const c=config();$('batteryValue').textContent=c.battery+'%';$('rangeValue').textContent=validConfig(c)?fmt(vehicleModel(c).availableRange)+' km':'—';if(state.route&&validConfig(c))renderResult();else if(state.route)clearResults();}
function pointMarker(kind,p){if(!map)return;const label=kind==='origin'?'A':kind==='stop'?'B':state.hasStop?'C':'B';const icon=L.divIcon({className:'',html:'<div class="point-marker '+(kind==='stop'?'stop':kind==='destination'?'destination':'')+'">'+label+'</div>',iconSize:[32,32],iconAnchor:[16,16]});const marker=L.marker([p.lat,p.lon],{icon,draggable:true,title:label+' · '+p.name}).addTo(pointLayers);const text=document.createElement('span');text.textContent=label+' · '+p.name;marker.bindPopup(text);marker.on('dragend',()=>{const ll=marker.getLatLng();setPoint(kind,{lat:ll.lat,lon:ll.lng,name:'Ponto no mapa ('+fmt(ll.lat,5)+', '+fmt(ll.lng,5)+')'});notify('Ponto alterado. Calcule a rota novamente.');});}
function renderPoints(){pointLayers?.clearLayers();for(const [kind,p] of Object.entries(state.points))if(p&&(kind!=='stop'||state.hasStop))pointMarker(kind,p);}
function setPoint(kind,p){state.points[kind]=p;$(kind).value=p.name;invalidate();renderPoints();}
function clearPoint(kind){state.points[kind]=null;$(kind).value='';invalidate();renderPoints();}
function toggleStop(on){state.hasStop=on;$('stopContainer').hidden=!on;['stop','chargeTarget','chargeMinutes'].forEach(id=>{$(id).required=on;$(id).disabled=!on;});$('addStop').hidden=on;$('destinationBadge').textContent=on?'C':'B';if(!on){state.points.stop=null;$('stop').value='';}invalidate();renderPoints();refreshModel();}
function selectMapPoint(kind){if(!map)return notify('O mapa está indisponível. Recarregue a página.',true);state.selecting=kind;$('selectionText').textContent=kind==='station'?'Toque no mapa para salvar uma recarga.':'Toque no mapa para marcar '+({origin:'a origem (A)',stop:'a recarga (B)',destination:'o destino ('+(state.hasStop?'C':'B')+')'}[kind])+'.';$('selectionBanner').hidden=false;$('stationPanel').hidden=true;map.getContainer().style.cursor='crosshair';if(innerWidth<=760)$('mapWorkspace').scrollIntoView({block:'start'});}
function useGPS(kind='origin'){if(!navigator.geolocation)return notify('Localização não disponível neste navegador.',true);notify('Localizando você…');const revision=state.revision;navigator.geolocation.getCurrentPosition(pos=>{if(revision!==state.revision)return;const p={lat:pos.coords.latitude,lon:pos.coords.longitude,name:'Minha localização'};setPoint(kind,p);map?.setView([p.lat,p.lon],15);notify('Localização definida. Confira o ponto no mapa.');},err=>notify(err.code===1?'Permita o acesso à localização ou escolha um ponto no mapa.':'Não foi possível obter sua localização. Tente pelo mapa.',true),{enableHighAccuracy:true,timeout:15000,maximumAge:30000});}
async function fetchJSON(url,timeout=18000,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(url,{...options,signal:controller.signal});if(!res.ok)throw new Error('Serviço indisponível ('+res.status+'). Tente novamente mais tarde.');return await res.json();}finally{clearTimeout(timer);}}
function chooseAddress(features,title){return new Promise(resolve=>{searchResolve=resolve;state.addressChoice=null;$('searchDescription').textContent=title;$('searchResults').replaceChildren();features.forEach(f=>{const p=f.properties,c=f.geometry.coordinates;const name=[p.name,p.street,p.housenumber].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(', ')||'Endereço';const detail=[p.district,p.city,p.state,p.country].filter(Boolean).join(' · ');const button=document.createElement('button');button.type='button';button.textContent=name;const small=document.createElement('small');small.textContent=detail;button.append(small);button.addEventListener('click',()=>{state.addressChoice={lat:c[1],lon:c[0],name:[name,p.city].filter(Boolean).join(' — ')};$('searchDialog').close();});$('searchResults').append(button);});$('searchDialog').showModal();});}
// Public services require modest, user-initiated use. Queues keep starts at least 1.1s apart.
function rateQueue(){let chain=Promise.resolve(),last=0;return task=>{const result=chain.then(async()=>{const wait=1100-(Date.now()-last);if(wait>0)await new Promise(r=>setTimeout(r,wait));last=Date.now();return task();});chain=result.catch(()=>{});return result;};}
const geocodeQueue=rateQueue(),routeQueue=rateQueue(),searchCache=new Map(),routeCache=new Map();
async function searchPlace(query){const key=query.trim().toLowerCase();if(searchCache.has(key))return searchCache.get(key);return geocodeQueue(async()=>{const center=map?.getCenter();const url='https://photon.komoot.io/api/?limit=5&q='+encodeURIComponent(query)+(center?'&lat='+center.lat+'&lon='+center.lng:'');const data=await fetchJSON(url);const features=(data.features||[]).filter(f=>f.geometry?.type==='Point'&&f.geometry.coordinates.length>=2&&f.geometry.coordinates.every(Number.isFinite));searchCache.set(key,features);return features;});}
async function resolvePoint(kind){if(state.points[kind])return state.points[kind];const query=$(kind).value.trim();if(!query)throw new Error('Preencha '+(kind==='origin'?'a origem':kind==='stop'?'a parada de recarga':'o destino')+'.');notify('Buscando endereço…');const features=await searchPlace(query+', '+$('city').value.trim());if(!features.length)throw new Error('Endereço não encontrado. Inclua a cidade ou escolha no mapa.');const selected=await chooseAddress(features,'Confirme '+(kind==='origin'?'a origem':kind==='stop'?'a recarga':'o destino')+' antes de calcular.');if(!selected)throw new Error('Busca cancelada.');return selected;}
async function routeLeg(a,b,vehicle){const profile=vehicle==='moto'?'car':'bike';const url='https://routing.openstreetmap.de/routed-'+profile+'/route/v1/driving/'+a.lon+','+a.lat+';'+b.lon+','+b.lat+'?overview=full&geometries=geojson&steps=false&generate_hints=false';if(routeCache.has(url))return routeCache.get(url);return routeQueue(async()=>{const data=await fetchJSON(url,22000);if(data.code!=='Ok'||!data.routes?.length)throw new Error('Não há rota pelas vias entre esses pontos. Escolha pontos próximos a uma rua.');const route=data.routes[0];if(!Number.isFinite(route.distance)||route.distance<1||!route.geometry?.coordinates?.length)throw new Error('Escolha origem e destino em locais diferentes.');if(data.waypoints?.some(w=>w.distance>400))throw new Error('Um ponto está longe das vias conhecidas. Aproxime o marcador de uma rua.');routeCache.set(url,route);return route;});}
async function calculateRoute(event){event?.preventDefault();if($('calculate').disabled)return;if(!$('routeForm').reportValidity())return;const c=config();if(!validConfig(c))return notify('Confira autonomia, peso e configuração de recarga.',true);cancelSelection();clearResults();const request=++state.request,revision=state.revision;$('calculate').disabled=true;$('findCity').disabled=true;$('calculate').querySelector('span').textContent='Calculando…';try{for(const kind of ['origin',...(state.hasStop?['stop']:[]),'destination']){const p=await resolvePoint(kind);if(request!==state.request||revision!==state.revision)return;state.points[kind]=p;$(kind).value=p.name;}renderPoints();notify('Calculando as vias de cada trecho…');const points=[state.points.origin,...(state.hasStop?[state.points.stop]:[]),state.points.destination,...($('roundTrip').checked?[state.points.origin]:[])],legs=[];for(let i=0;i<points.length-1;i++){if(request!==state.request)return;legs.push(await routeLeg(points[i],points[i+1],c.vehicle));}if(request!==state.request||revision!==state.revision)return;state.route={legs,roundTrip:$('roundTrip').checked,hasStop:state.hasStop,departure:Date.now()};renderResult();drawRoute();$('toast').hidden=true;if(innerWidth<=760)$('mapWorkspace').scrollIntoView({block:'start'});}catch(error){if(request===state.request)notify(error.name==='AbortError'?'O serviço demorou a responder. Tente novamente.':error.message,true);}finally{$('calculate').disabled=false;$('findCity').disabled=false;$('calculate').querySelector('span').textContent='Calcular minha rota';}}
function drawRoute(){if(!map)return;routeLayers.clearLayers();state.route.legs.forEach((leg,i)=>{const returning=state.route.roundTrip&&i===state.route.legs.length-1;L.geoJSON(leg.geometry,{style:{color:'#163744',weight:9,opacity:.6}}).addTo(routeLayers);L.geoJSON(leg.geometry,{style:{color:returning?'#187aab':'#19b777',weight:returning?4:6,opacity:1,dashArray:returning?'9 8':undefined}}).addTo(routeLayers);});fitRoute();}
function fitRoute(){if(!map)return;const bounds=routeLayers?.getBounds();if(bounds?.isValid())map.fitBounds(bounds,{paddingTopLeft:[50,135],paddingBottomRight:[50,Math.min(map.getSize().y*.6,$('result').offsetHeight+65)],maxZoom:16});else if(Object.values(state.points).some(Boolean))map.fitBounds(Object.values(state.points).filter(Boolean).map(p=>[p.lat,p.lon]),{padding:[65,65],maxZoom:15});}
function duration(minutes){const n=Math.max(1,Math.ceil(minutes));return n<60?n+' min':Math.floor(n/60)+'h '+String(n%60).padStart(2,'0')+'min';}
function clockAt(minutes){const date=new Date(state.route.departure+Math.ceil(minutes)*60000),base=new Date(state.route.departure);return date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+(date.toDateString()!==base.toDateString()?' · '+date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'');}
function batteryText(leg){return leg.reached?'~'+Math.floor(leg.remaining)+'%':'Não chega';}
function renderResult(){if(!state.route)return;const c=config();if(!validConfig(c))return;state.route.departure=Date.now();state.config=c;const r=calculateEnergy(state.route.legs,c,state.route.hasStop,state.route.roundTrip);state.energy=r;$('result').className='result'+(!r.reachable?' danger':r.lowReserve?' warning':'');$('emptyResult').hidden=true;$('resultContent').hidden=false;const title=r.reachable?(r.lowReserve?'Vai chegar com pouca reserva':state.route.roundTrip?'Dá para ir e voltar':'Dá para chegar'):(state.route.hasStop&&!r.states[0].reached?'Você não alcança a recarga':r.destination.reached?'A bateria não cobre a volta':'A bateria não cobre a ida');$('resultTitle').textContent=title;$('statusSymbol').textContent=r.reachable?(r.lowReserve?'!':'✓'):'!';$('resultSubtitle').textContent=r.reachable?(r.lowReserve?'Algum trecho termina com menos de 15% de bateria.':'Previsão com os ajustes do seu veículo.'):'Ajuste o trajeto ou recarregue antes do trecho insuficiente.';$('totalDistance').textContent=km(r.totalDistance);$('distanceDetail').textContent=km(r.outboundDistance)+' ida'+(r.returned?' · '+km(r.returnDistance)+' volta':'');$('totalTime').textContent=duration(r.totalMinutes);$('timeDetail').textContent=r.chargeWait?r.chargeWait+' min de recarga incluídos':'Sem trânsito em tempo real';$('arrivalBattery').textContent=batteryText(r.destination);$('arrivalBattery').style.color=r.destination.reached?'var(--green)':'var(--red)';$('arrivalClock').textContent=r.destination.reached?'Chegada ~'+clockAt(r.outboundMinutes):'Recarga necessária antes da chegada';$('returnBatteryLabel').textContent=r.returned?'Bateria na volta':'Reserva recomendada';$('returnBattery').textContent=r.returned?batteryText(r.returned):'15%';$('returnBattery').style.color=r.returned&&!r.returned.reached?'var(--red)':'var(--green)';$('returnClock').textContent=r.returned?(r.returned.reached?'De volta ~'+clockAt(r.totalMinutes):'Recarga necessária para voltar'):'Planeje uma margem';$('itinerary').replaceChildren();r.states.forEach((leg,i)=>{const labels=state.route.hasStop?['A → B · recarga','B → C · destino','C → A · volta']:['A → B · destino','B → A · volta'];const span=document.createElement('span');span.textContent=labels[i]+' '+km(leg.distance)+' · '+batteryText(leg);$('itinerary').append(span);});if(state.route.hasStop){const span=document.createElement('span');span.textContent=r.states[0].reached?'Recarga em B: +'+fmt(r.chargeAdded,0)+' pontos percentuais'+(r.chargeAdded?' em '+r.chargeWait+' min (informados)':' · carga já acima da meta'):'Recarga em B indisponível: bateria insuficiente para alcançá-la.';$('itinerary').append(span);}$('resultNote').textContent='Estimativa, não garantia. '+(r.returned?'Volta imediata, sem permanência no destino. ':'')+(state.route.hasStop?'Recarga informada por você.':'Mantenha reserva para imprevistos.');$('mapTitle').textContent=state.route.roundTrip?'Ida em verde · volta em azul':'Seu caminho até o destino';}
function summary(){if(!state.route||!state.energy)return '';const r=state.energy,c=state.config;return ['⚡ UrbanVolt — previsão de trajeto',VEHICLES[c.vehicle].name+' · '+({eco:'Eco',normal:'Normal',sport:'Sport'}[c.mode]),'Origem (A): '+state.points.origin.name,...(state.route.hasStop?['Recarga (B): '+state.points.stop.name,'Carga alvo: '+c.chargeTarget+'% · tempo informado: '+c.chargeMinutes+' min']:[]),'Destino ('+(state.route.hasStop?'C':'B')+'): '+state.points.destination.name,'Bateria inicial: '+c.battery+'% · Autonomia base: '+c.range+' km · Peso: '+c.weight+' kg','Distância: '+km(r.totalDistance)+' ('+km(r.outboundDistance)+' ida'+(r.returned?', '+km(r.returnDistance)+' volta':'')+')','Tempo previsto: '+duration(r.totalMinutes),'Chegada: '+(r.destination.reached?'~'+clockAt(r.outboundMinutes)+' · bateria: '+batteryText(r.destination):'inviável com a carga atual'),...(r.returned?['Retorno: '+(r.returned.reached?'~'+clockAt(r.totalMinutes)+' · bateria: '+batteryText(r.returned):'inviável com a carga atual')]:[]),$('resultTitle').textContent,'Estimativa sem trânsito ao vivo, relevo ou desgaste da bateria. '+(r.returned?'Volta imediata, sem permanência no destino.':''),'Pontos: '+[state.points.origin,...(state.route.hasStop?[state.points.stop]:[]),state.points.destination].map(p=>p.lat.toFixed(5)+','+p.lon.toFixed(5)).join(' → ')].join('\n');}
async function copySummary(){try{await navigator.clipboard.writeText(summary());notify('Resumo copiado.');}catch{notify('Não foi possível copiar. Use o botão WhatsApp.',true);}}
function initMap(){if(typeof L==='undefined'){$('mapFailure').hidden=false;return;}map=L.map('map',{zoomControl:false}).setView([-23.55052,-46.633309],13);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> · <a href="https://routing.openstreetmap.de/about.html">FOSSGIS/OSRM</a> · <a href="https://www.openstreetmap.org/fixthemap">Corrigir mapa</a>'}).addTo(map);let tileErrors=0;tiles.on('tileerror',()=>{if(++tileErrors===3)notify('Algumas partes do mapa não carregaram. Confira sua conexão.',true);});L.control.zoom({position:'topright'}).addTo(map);routeLayers=L.featureGroup().addTo(map);pointLayers=L.layerGroup().addTo(map);stationLayers=L.layerGroup().addTo(map);map.on('click',e=>{if(!state.selecting)return;const kind=state.selecting;cancelSelection();const p={lat:e.latlng.lat,lon:e.latlng.lng,name:'Ponto no mapa ('+fmt(e.latlng.lat,5)+', '+fmt(e.latlng.lng,5)+')'};if(kind==='station')openSaveStation(p);else{setPoint(kind,p);notify('Ponto definido. Toque em Calcular minha rota.');}});}
function loadSaved(){try{const data=JSON.parse(localStorage.getItem('urbanvolt_saved_stations')||'[]');if(!Array.isArray(data))throw Error();state.saved=data.filter(p=>p&&Number.isFinite(p.lat)&&Math.abs(p.lat)<=90&&Number.isFinite(p.lon)&&Math.abs(p.lon)<=180&&typeof p.name==='string').map((p,i)=>({id:String(p.id||('local-'+i)),lat:p.lat,lon:p.lon,name:p.name.slice(0,100),info:typeof p.info==='string'?p.info.slice(0,300):''}));}catch{state.saved=[];notify('Não foi possível ler os pontos salvos neste navegador.',true);}}
function persistSaved(next){try{localStorage.setItem('urbanvolt_saved_stations',JSON.stringify(next));state.saved=next;renderStations();return true;}catch{notify('O navegador não permitiu salvar. Verifique o armazenamento local.',true);return false;}}
function openSaveStation(p){state.pendingStation=p;$('stationName').value=p.name.startsWith('Ponto no mapa')?'':p.name;$('stationInfo').value=p.info||'';$('stationCoordinates').textContent=fmt(p.lat,5)+', '+fmt(p.lon,5);$('saveDialog').showModal();}
function useStation(p){toggleStop(true);setPoint('stop',{lat:p.lat,lon:p.lon,name:p.name});map?.closePopup();$('stationPanel').hidden=true;notify('Recarga adicionada. Confira a meta de carga e calcule a rota.');$('stopContainer').scrollIntoView({block:'center'});}
function stationCard(p,saved,compact=false){const box=document.createElement('div');box.className=compact?'':'station-card';const kind=document.createElement('div');kind.className='station-kind';kind.textContent=saved?'Salvo neste navegador':'Ponto mapeado · disponibilidade não verificada';const h=document.createElement('h3');h.textContent=p.name;const info=document.createElement('p');info.textContent=p.info||'Confirme tomada, acesso e horário no local.';const actions=document.createElement('div');actions.className='row';const use=document.createElement('button');use.className='button small primary';use.textContent='Usar como recarga B';use.addEventListener('click',()=>useStation(p));const save=document.createElement('button');save.className='button small';save.textContent=saved?'Excluir':'Salvar';save.addEventListener('click',()=>{if(saved){if(!window.confirm('Excluir “'+p.name+'” dos pontos salvos neste navegador?'))return;if(persistSaved(state.saved.filter(s=>s.id!==p.id))){map?.closePopup();notify('Ponto excluído.');}}else openSaveStation(p);});actions.append(use,save);box.append(kind,h,info,actions);return box;}
function renderStations(){stationLayers?.clearLayers();$('savedCount').textContent=state.saved.length;$('publicTab').setAttribute('aria-pressed',String(state.stationTab==='public'));$('savedTab').setAttribute('aria-pressed',String(state.stationTab==='saved'));const list=state.stationTab==='saved'?state.saved:state.publicStations;$('stationList').replaceChildren();if(state.stationsBusy&&state.stationTab==='public'){$('stationList').textContent='Buscando pontos de recarga…';}else if(!list.length){const p=document.createElement('p');p.className='help';p.textContent=state.stationTab==='public'&&state.stationError?state.stationError:state.stationTab==='saved'?'Você ainda não salvou pontos. Marque uma tomada no mapa para começar.':state.publicSearched?'Nenhum ponto mapeado encontrado nesta região. Você pode cadastrar um ponto próprio.':'Busque os pontos na área visível do mapa.';$('stationList').append(p);}else list.forEach(p=>$('stationList').append(stationCard(p,state.stationTab==='saved')));if(state.stationTab==='public'&&!state.stationsBusy){const refresh=document.createElement('button');refresh.className='button full';refresh.textContent='Buscar na área do mapa';refresh.addEventListener('click',fetchStations);$('stationList').append(refresh);}if(map){[...state.publicStations.map(p=>({...p,saved:false})),...state.saved.map(p=>({...p,saved:true}))].forEach(p=>{const icon=L.divIcon({className:'station-marker'+(p.saved?' saved':''),html:'ϟ',iconSize:[27,27],iconAnchor:[13,13]});L.marker([p.lat,p.lon],{icon,title:p.name}).addTo(stationLayers).bindPopup(stationCard(p,p.saved,true));});}}
function showStations(tab){state.stationTab=tab;$('stationPanel').hidden=false;renderStations();if(innerWidth<=760)$('mapWorkspace').scrollIntoView({block:'start'});}
const stationCache=new Map();let lastStationRequest=0;
async function fetchStations(){showStations('public');if(!map)return notify('Mapa indisponível.',true);if(state.stationsBusy)return;const b=map.getBounds(),distance=b.getSouthWest().distanceTo(b.getNorthEast());if(distance>30000)return notify('Aproxime o mapa para uma área de até 30 km e busque novamente.',true);const bbox=[b.getSouth(),b.getWest(),b.getNorth(),b.getEast()].map(n=>n.toFixed(4)).join(',');const cached=stationCache.get(bbox);if(cached&&Date.now()-cached.at<300000){state.publicStations=cached.points;state.publicSearched=true;return renderStations();}if(Date.now()-lastStationRequest<10000)return notify('Aguarde alguns segundos antes de buscar outra área.');lastStationRequest=Date.now();state.stationError='';state.stationsBusy=true;renderStations();try{const query='[out:json][timeout:20];nwr["amenity"="charging_station"]('+bbox+');out center tags;';const data=await fetchJSON('https://overpass.private.coffee/api/interpreter?data='+encodeURIComponent(query),28000);if(data.remark)throw new Error('A busca de recargas está ocupada. Tente novamente mais tarde.');state.publicStations=(data.elements||[]).map(p=>{const t=p.tags||{},lat=p.lat??p.center?.lat,lon=p.lon??p.center?.lon;const access={yes:'acesso público',permissive:'acesso permitido',private:'acesso privado',customers:'somente clientes',no:'acesso restrito'}[t.access]||'acesso a confirmar';const sockets=Object.entries(t).filter(([k,v])=>k.startsWith('socket:')&&k.split(':').length===2&&v!=='0'&&v!=='no').map(([k,v])=>k.slice(7).replaceAll('_',' ')+' ('+v+')').join(', ');return {id:p.type+'-'+p.id,lat,lon,name:t.name||t.operator||'Ponto de recarga',info:[access,sockets?'Conectores: '+sockets:'Tomada não informada',t.opening_hours?'Horário: '+t.opening_hours:''].filter(Boolean).join(' · ')};}).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));state.publicSearched=true;stationCache.set(bbox,{at:Date.now(),points:state.publicStations});notify(state.publicStations.length+' pontos mapeados nesta região.');}catch(e){state.stationError='Não foi possível consultar os pontos agora. Tente novamente ou salve uma tomada conhecida no mapa.';notify(e.name==='AbortError'?'A busca de recargas demorou a responder. Tente novamente.':e.message,true);}finally{state.stationsBusy=false;renderStations();}}
document.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>selectMapPoint(b.dataset.select)));document.querySelectorAll('[data-clear]').forEach(b=>b.addEventListener('click',()=>clearPoint(b.dataset.clear)));
document.querySelectorAll('[data-vehicle]').forEach(b=>b.addEventListener('click',()=>{if(state.vehicle===b.dataset.vehicle)return;state.vehicle=b.dataset.vehicle;document.querySelectorAll('[data-vehicle]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('fullRange').value=VEHICLES[state.vehicle].range;$('profileLabel').textContent=state.vehicle==='moto'?'Perfil de automóvel · confira acesso para motos':'Perfil de bicicleta · rotas pelas vias';invalidate();refreshModel();}));
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));refreshModel();}));
['origin','stop','destination'].forEach(kind=>$(kind).addEventListener('input',()=>{state.points[kind]=null;invalidate();renderPoints();}));['battery','fullRange','weight','chargeTarget','chargeMinutes'].forEach(id=>$(id).addEventListener('input',refreshModel));$('city').addEventListener('input',()=>{state.points={origin:null,stop:null,destination:null};invalidate();renderPoints();});
$('roundTrip').addEventListener('change',invalidate);$('routeForm').addEventListener('submit',calculateRoute);$('addStop').addEventListener('click',()=>toggleStop(true));$('removeStop').addEventListener('click',()=>toggleStop(false));$('originGPS').addEventListener('click',()=>useGPS('origin'));$('destinationGPS').addEventListener('click',()=>useGPS('destination'));$('mapGPS').addEventListener('click',()=>useGPS());$('cancelSelection').addEventListener('click',cancelSelection);$('fitRoute').addEventListener('click',fitRoute);$('showMap').addEventListener('click',()=>$('mapWorkspace').scrollIntoView({block:'start'}));
$('closeSearch').addEventListener('click',()=>$('searchDialog').close());$('searchDialog').addEventListener('close',()=>{if(searchResolve){const resolve=searchResolve;searchResolve=null;resolve(state.addressChoice||null);state.addressChoice=null;}});
$('findCity').addEventListener('click',async()=>{if($('calculate').disabled)return;const city=$('city').value.trim();if(!city)return notify('Informe uma cidade.',true);try{$('findCity').disabled=true;$('calculate').disabled=true;const features=await searchPlace(city);if(!features.length)return notify('Cidade não encontrada.',true);const p=await chooseAddress(features,'Escolha a cidade ou região.');if(p)map?.setView([p.lat,p.lon],13);}catch{notify('A busca está indisponível. Você pode navegar pelo mapa.',true);}finally{$('findCity').disabled=false;$('calculate').disabled=false;}});
$('copySummary').addEventListener('click',copySummary);$('whatsapp').addEventListener('click',()=>{const message=summary();if(message)window.open('https://wa.me/?text='+encodeURIComponent(message),'_blank','noopener,noreferrer');});
$('savedButton').addEventListener('click',()=>showStations('saved'));$('stationsButton').addEventListener('click',fetchStations);$('publicTab').addEventListener('click',()=>showStations('public'));$('savedTab').addEventListener('click',()=>showStations('saved'));$('closeStations').addEventListener('click',()=>$('stationPanel').hidden=true);$('saveMapPoint').addEventListener('click',()=>selectMapPoint('station'));$('cancelSave').addEventListener('click',()=>$('saveDialog').close());$('saveStationForm').addEventListener('submit',e=>{e.preventDefault();const p=state.pendingStation,name=$('stationName').value.trim();if(!p||!name)return;const duplicate=state.saved.some(s=>Math.abs(s.lat-p.lat)<.00001&&Math.abs(s.lon-p.lon)<.00001&&s.name===name);if(duplicate)return notify('Este ponto já está salvo.',true);const item={id:typeof crypto.randomUUID==='function'?crypto.randomUUID():String(Date.now()),lat:p.lat,lon:p.lon,name,info:$('stationInfo').value.trim()};if(persistSaved([...state.saved,item])){$('saveDialog').close();state.pendingStation=null;showStations('saved');notify('Ponto salvo neste navegador.');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')cancelSelection();});
initMap();loadSaved();renderStations();refreshModel();
